package com.example.settlersofcatan;

import com.example.game.GameFramework.GameMainActivity;
import com.example.game.GameFramework.LocalGame;
import com.example.game.GameFramework.gameConfiguration.GameConfig;
import com.example.game.GameFramework.gameConfiguration.GamePlayerType;
import com.example.game.GameFramework.infoMessage.GameState;
import com.example.game.GameFramework.players.GamePlayer;

import java.util.ArrayList;
/*
    Our game meets the majority of the requirements. The GUI is functional, and the bugs reported in the Test to Succeed session have been resolved.
    However, 4-player mode is not yet functional as we had difficulty synchronizing the AI players.
    The main issue was our complex AI was hard-coded to be player 2 for testing purposes, but out attempts to alter this resulted in nullpointer errors in LocalGame and GameState
    Given an extra week this could have been resolved but we ran out of time. In addition, playing purchased development cards is not functional, as the Spinner class in Android is incredibly opaque.
    The documentation is lacking clarity at best and outright incomplete at worst, so the selection of a card to be played in the drop-down menu causes a crash.
    We are planning on attending office hours to get some guidance, as the resources on the internet were also lacking in clarity.

    Additional features since Alpha:
    GUI has numbers
    Settlement locations are checked accurately
    Possible build locations for settlements are now highlighted using black boxes
    Same for building cities
    Trading with the bank is now possible, if you have 4 or more of a resource the button will highlight
        once you are in trading mode, select the resource you want to give and the resource you want to get.
    The UI also now includes an indicator for the dice that were rolled (the dice display the actual numbers generated by the random number generator)
    The UI also now includes an indicator for the current class state (ie. building, trading, not your turn, discarding because of a 7) making the UX much more streamlined
    Roads can no longer be placed in the ether by selecting the space between valid coordinates
    Roads can no longer be constructed as highways that cut hexes, their max length is now properly restricted to one segment.
    Touch event handling has been improved and accuracy has been increased to better prevent miss-clicks
    Settlements upgraded to cities are now destroyed, and no longer cause issues with victory points and road construction
 */
/**
 * CatanMainActivity initializes and kicks off the GameFramework, as well as maintaining the configuration and default configuration of the game
 *
 * @author Anthony Albelo
 * @author Eric Su
 * @author Connor Santa Monica
 * @author Reiss Oliveross
 * @author Ryley vargas
 *
 * @Version October 30th 2023
 */
public class CatanMainActivity extends GameMainActivity {

    //same port number as lab project so that ik this is not causing an error
    private static final int PORT_NUMBER = 2278;

    /**
     * Create a default configuration for our game
     * @return a GameConfig object that represents the default configuration that you specify
     */
    @Override
    public GameConfig createDefaultConfig() {
        //list of allowed player types
        ArrayList<GamePlayerType> playerTypes = new ArrayList<GamePlayerType>();
        //local human player
        playerTypes.add(new GamePlayerType("Local Human Player") {
            public GamePlayer createPlayer(String name) {return new CatanHumanPlayer(name);}});
        playerTypes.add(new GamePlayerType("Rolls Dice") {
            public GamePlayer createPlayer(String name) {return new CatanAI(name);}});
        playerTypes.add(new GamePlayerType("Complex AI") {
            public GamePlayer createPlayer(String name) {return new CatanSimpleAI(name);}});

        //create a default gameConfig
        GameConfig defaultConfig = new GameConfig(playerTypes, 2, 4, "Settlers of Catan", PORT_NUMBER);
        defaultConfig.addPlayer("Human", 0);
        defaultConfig.addPlayer("SkyNet but it actually moves", 2);
        defaultConfig.setRemoteData("Remote Human Player", "", 0);
        return defaultConfig;
    }

    @Override
    public LocalGame createLocalGame(GameState gameState) {
        return new CatanLocalGame();
    }
}